### ISSUE TITLE
ImportError: No module named tsys01

### ISSUE THREAD

**Issue by ChrisTorres342** [bluerobotics/tsys01-python#5] opened 2019-03-01 22:51 UTC
I have installed smbus onto my raspberry pi using the command "sudo apt-get install python-smbus". This seemed to have been successful, however I get the error mentioned in the title when I try to run the example code. Is there any way you could help me out with this issue? Thanks :)

-Chris

**Comment by patrickelectric** [comment] 2019-03-20 11:13
Duplicate of https://github.com/bluerobotics/tsys01-python/issues/4

**Closed as completed by patrickelectric** 2019-03-20 11:13 UTC
